services:
  pagamentos-ms:
    build: ./pagamentos
    volumes:
      - ./pagamentos:/app
      - ../../../../Users/caina/.m2:/root/.m2
    working_dir: /app
    depends_on:
      - pagamentos-db
      - eureka-server
    links:
      - pagamentos-db
      - eureka-server
    command: "./mvnw spring-boot:run"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url": "jdbc:mysql://pagamentos-db:3307/alurafood_pagamentos?createDatabaseIfNotExist=true",
            "spring.datasource.username": "alurafood",
            "spring.datasource.password": "password",
            "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
            "spring.jpa.show-sql": "true",
            "spring.application.name": "pagamentos-ms",
            "eureka.client.serviceUrl.defaultZone": "http://eureka-server:8761/eureka/",
            "server.port": "0"
          }'
#    ports:
#      - "8081:8081"
#    hostname: localhost

  pagamentos-db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alurafood_pagamentos
      MYSQL_USER: alurafood
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"

  pedidos-ms:
    build: ./pedidos
    deploy:
      mode: replicated
      replicas: 3
#      endpoint_mode: dnsrr
    volumes:
      - ./pedidos:/app
      - ../../../../Users/caina/.m2:/root/.m2
    working_dir: /app
    depends_on:
      - pedidos-db
      - eureka-server
    links:
      - pagamentos-db
      - eureka-server
    command: "./mvnw spring-boot:run"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url": "jdbc:mysql://pedidos-db:3308/alurafood_pedidos?createDatabaseIfNotExist=true",
            "spring.datasource.username": "alurafood",
            "spring.datasource.password": "password",
            "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
            "spring.jpa.show-sql": "true",
            "spring.application.name": "pedidos-ms",
            "eureka.client.serviceUrl.defaultZone": "http://eureka-server:8761/eureka/",
            "eureka.instance.instance-id=": "$${spring.application.name}:$${random.int}",
            "server.port":"0"
          }'
#    ports:
#      - "8082:8082"
#    hostname: localhost

  pedidos-db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alurafood_pedidos
      MYSQL_USER: alurafood
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    volumes:
      - ./eureka-server:/app
      - ../../../../Users/caina/.m2:/root/.m2
    working_dir: /app
    command: "./mvnw spring-boot:run"
    ports:
      - "8761:8761"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    volumes:
      - ./gateway:/app
      - ../../../../Users/caina/.m2:/root/.m2
    working_dir: /app
    depends_on:
      - eureka-server
    links:
      - eureka-server
    command: "./mvnw spring-boot:run"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.application.name": "gateway",
            "eureka.client.serviceUrl.defaultZone": "http://eureka-server:8761/eureka/",
            "server.port":"8762"
          }'
    ports:
      - "8762:8762"
#    hostname: localhost

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"