version: '3.9'
services:
  dev:
    container_name: pagamentos-api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - pagamentos-db
    volumes:
      - ./:/app
      - ../../../../../Users/caina/.m2:/root/.m2
    working_dir: /app
    command: "sh run.sh"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url": "jdbc:mysql://pagamentos-db:3306/alurafood_pagamentos",
            "spring.datasource.username": "alurafood",
            "spring.datasource.password": "password",
            "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
            "spring.jpa.show-sql": "true",
            "server.port": "8080",
            "eureka.client.enabled": "false"
          }'
    ports:
      - "8080:8080"

  pagamentos-db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alurafood_pagamentos
      MYSQL_USER: alurafood
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"